print('votre nom : ')
nom=input()
print(nom, 'c\'est un joli nom')
print(type(nom))
prenom=input('votre prenom : ')
print('Bonjour ', prenom,' ',nom,'\nBienvenu parmis nous')
age=int(input('votre annee de naissance : '))
print('Informations Personnelles: \n Nom : ',nom, '\tPrenom : ',prenom,'\nAge : ',2017-age,'ans')
